POST http://localhost:3000/api/addHarddrive HTTP/1.1
Content-Type: application/json

{
    "user_name": "John",
    "address": "123 Main St",
    "contact": "john.doe@example.com",
    "model_name": "Intel Core i9",
    "hd_interface": "LGA 1200",
    "form_factor": "Z490",
    "cooling": "125W",
    "description": "4.0",
    "image": "http://example.com/image.jpg",
    "rest": "Additional info"
}