POST http://localhost:3000/api/addMotherboard HTTP/1.1
Content-Type: application/json

{
    "user_name": "John",
    "address": "123 Main St",
    "contact": "john.doe@example.com",
    "model_name": "Intel Core i9",
    "socket_type": "LGA 1200",
    "chipset": "Z490",
    "ddr": "DDR4",
    "pcie": "random",
    "form_factor": "4.0",
    "power_connect": "some",
    "description": "Additional info",
    "image": "abcdefg",
    "rest": "none"
}